import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { NAVIGATION_ITEMS } from '../enums/navigation';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <Link href={NAVIGATION_ITEMS.SHOP} passHref>
      <div className={styles.container}>
        <Head>
          <title>･*。 　 　･° 　　　°。 * 。 　　　　　　 ･°</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/images/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Image
            src="/images/mawsoni-hero-animation.gif"
            className={styles.heroAnimation}
            layout="fill"
            alt=""
          ></Image>
        </main>
      </div>
    </Link>
  );
};

export default Home;
